# Generated by Django 4.1.7 on 2023-02-27 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_playlistssongs_playlistssong"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlistssong",
            name="next",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_song",
                to="core.playlistssong",
            ),
        ),
        migrations.AlterField(
            model_name="playlistssong",
            name="previous",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="previous_song",
                to="core.playlistssong",
            ),
        ),
    ]
